### ISSUE TITLE
Models Creation

### ISSUE THREAD

**Issue by dmbf29** [dmbf29/predictor-api#1]
- [x] setup Devise
- [x] create models / default values / enums
- [x] build associations
- [x] add validations
- [x] add tokens

**Comment by trouni** [comment]
@dmbf29 FYI, we can't use `devise-token_authenticatable` for tokens in our case because it only allows for signing in (signup is not handled). You should still setup Devise the same way, but we will need to use [`devise_token_auth`](https://github.com/lynndylanhurley/devise_token_auth) for the API authentication. I created issue #5 for this.
